##
# DevShop: DevMaster Server with Apache
#

---
- hosts: all
  user: root
  roles:
    - opendevshop.aegir-user
    - opendevshop.aegir-apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - opendevshop.devmaster

  vars:
    __php_mysql_package: php5-mysql
